name: 'Sentry Artifacts'
description: 'Handles uploading coverage/test artifacts to codecov'

runs:
  using: "composite"
  steps:
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        directory: .artifacts
        verbose: true
