name: 'Sentry Artifacts'
description: 'Handles uploading coverage/test artifacts to codecov'

runs:
  using: "composite"
  steps:
    - name: debug
      uses: actions/upload-artifact@v2
      with:
        retention-days: 3
        name: debug
        path: .artifacts/visual-snapshots/acceptance-mobile

    - name: Upload to codecov
      shell: bash
      run: |
        coverage_files=$(ls .artifacts/*coverage.xml || true)
        if [[ -n "$coverage_files" || -f .artifacts/coverage/cobertura-coverage.xml ]]; then
          bash <(curl -s https://codecov.io/bash) -v
        fi
