name: 'Run Smoke Tests'
on:
  push:  # This is for testing only -- DELETE BEFORE LANDING
    branches:
      - byk/ci/smoke-tests
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  smoke_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install playwright
        run: yarn add --global playright @playwright/test
      - name: Install operating system dependencies
        run: playwright install-deps
      - name: Run your tests
        run: playwright test --browser all tests/smoke
